# Jekyll configuration

title: GNU/Weeb
author: 
  name: GNU/Weeb Contributors (https://github.com/GNUWeeb/www.gnuweeb.org/graphs/contributors)
description: > # this means to ignore newlines until "show_excerpts:"
  We are working to build community through Open Source technology
show_excerpts: false # set to true to show excerpts on the homepage
# Date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
gnuweeb:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github: gnuweeb
    telegram: GNUWeeb
    reddit: gnuweeb
    # twitter: jekyllrb
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # GitHub instances
    # github:
    # - username: GNUWeeb
    #   instance: hello@gnuweeb.org

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


exclude:
  - bin
  - "CODE_OF_CONDUCT.md"
  - "gnuweeb.gemspec"
  - "LICENSE"
  - "README.md"
